export const ADD_BUILDINGS = 'ADD_BUILDINGS';
export const CLEAR_BUILDINGS = 'CLEAR_BUILDINGS';
export const CAROUSEL_UPDATE = 'CAROUSEL_UPDATE';
export const FORM_UPDATE = 'FORM_UPDATE';
export const UPDATE_COORDS = 'UPDATE_COORDS';
